import { Quicksand } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="hydrated">
      <body
        className={`${quicksand.className} antialiased`}
        data-new-gr-c-s-check-loaded="14.1256.0"
        data-gr-ext-installed=""
      >
        {children}
      </body>
    </html>
  );
}
